usage: train_model.py [-h] config dataset
train_model.py: error: unrecognized arguments: 2
cuda:0